### ISSUE TITLE
this is steal from pretendo network

### ISSUE THREAD

**Issue by 00cedke** [RubyNetworkTeam/account#14]
this is steal from pretendo network

**Comment by 00cedke** [comment]
this is steal from pretendo network

**Comment by 00cedke** [comment]
this is steal from pretendo network

**Comment by 00cedke** [comment]
this is steal from pretendo network

**Comment by 00cedke** [comment]
this is steal from pretendo network

**Comment by 00cedke** [comment]
this is steal from pretendo network

**Comment by 00cedke** [comment]
this is steal from pretendo network

**Comment by 00cedke** [comment]
this is steal from pretendo network

**Comment by 00cedke** [comment]
this is steal from pretendo network

**Comment by 00cedke** [comment]
this is steal from pretendo network

**Comment by 00cedke** [comment]
this is steal from pretendo network

**Comment by 00cedke** [comment]
this is steal from pretendo network

**Comment by 00cedke** [comment]
this is steal from pretendo network

**Comment by 00cedke** [comment]
this is steal from pretendo network

**Comment by 00cedke** [comment]
this is steal from pretendo network

**Comment by 00cedke** [comment]
this is steal from pretendo network

**Comment by 00cedke** [comment]
this is steal from pretendo network

**Comment by PokeyManatee4** [comment]
I don't steal unlike you and if you have a real issue you can fuck off
